[toolchain]
channel = "nightly-2026-05-01"
components = ["rust-src", "rustfmt", "clippy", "llvm-tools-preview"]
targets = ["riscv64gc-unknown-none-elf", "aarch64-unknown-none", "x86_64-unknown-none"]
profile = "minimal"
