#!/usr/bin/env python3
"""Generate the POSIX-shim export contract from its Rust source."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "libs/api/src/services/posix"
OUT = ROOT / "docs/guides/posix-shim-contract.generated.md"

# Normal exported functions plus macro-generated libm wrappers.
functions = []
for path in sorted(SRC.glob("*.rs")):
    text = path.read_text()
    for name in re.findall(r"#\[no_mangle\]\s*(?:pub )?(?:unsafe )?extern \"C\" fn ([A-Za-z_][A-Za-z0-9_]*)", text):
        functions.append((name, path.name))
    for name in re.findall(r"math[12]_f(?:32|64)!\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,", text):
        functions.append((name, path.name))

# These names deliberately return failure rather than silently succeeding.
refusals = {"_fcntl", "_execve", "_fork", "_wait", "_link", "_kill", "fork", "mprotect"}
null_refusals = {"dlopen", "mmap"}

def semantics(name, source):
    if name in null_refusals:
        return "Unsupported; returns `NULL` and performs no operation."
    if name in refusals:
        return "Unsupported; returns `-1` and performs no operation."
    if source == "math.rs":
        return "C99 math bridge backed by Rust `libm`."
    if source == "strings.rs":
        return "C memory/string primitive; caller supplies valid C buffers."
    if source == "alloc.rs":
        return "Cell heap allocation or C++ ABI allocation support."
    if source == "net.rs":
        return "TCP-only Net IPC wrapper; invalid arguments return `-1`."
    if source == "entropy.rs":
        return "Kernel random service; invalid buffer/length returns `-1`."
    if source == "stdio.rs":
        return "Unbuffered shim stdio over Cellos descriptors."
    if source == "setjmp.rs":
        return "Architecture-specific non-local jump primitive."
    if source == "cxxabi.rs":
        return "Freestanding C++ ABI support; not hosted C++."
    return "POSIX-shim syscall/VFS/time/process wrapper; see source preconditions."

rows = [
    "# POSIX shim export contract (generated)",
    "",
    "Do not edit this file. Run `python3 scripts/gen-posix-shim-contract.py` after changing `libs/api/src/services/posix/`.",
    "The POSIX-shim tier is static-only. Symbols absent below are unsupported and must not be assumed to link.",
    "",
    "| Symbol | Tier | Source | Semantics / failure |",
    "|---|---|---|---|",
]
for name, source in sorted(set(functions)):
    rows.append(f"| `{name}` | POSIX shim | `{source}` | {semantics(name, source)} |")
rendered = "\n".join(rows) + "\n"

sysio = (SRC / "sysio.rs").read_text()
for name in refusals - {"fork"}:
    if not re.search(rf"fn {name}\([^)]*\)[^{{]*\{{\s*-1\s*\}}", sysio, re.S):
        raise SystemExit(f"contract violation: {name} must return -1")
if not re.search(r"fn fork\(\)[^{]*\{\s*_fork\(\)\s*\}", sysio, re.S):
    raise SystemExit("contract violation: fork must delegate to _fork")
for name in null_refusals:
    if not re.search(rf"fn {name}\([^)]*\)[^{{]*\{{\s*core::ptr::null_mut\(\)\s*\}}", sysio, re.S):
        raise SystemExit(f"contract violation: {name} must return NULL")

if "--check" in sys.argv:
    if not OUT.exists() or OUT.read_text() != rendered:
        raise SystemExit(f"contract drift: run {Path(__file__).relative_to(ROOT)}")
    print(f"OK: {OUT.relative_to(ROOT)} is current ({len(functions)} exports)")
else:
    OUT.write_text(rendered)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(functions)} exports)")
