#!/usr/bin/env python3
"""Generate the canonical moving code-size metrics used by Cellos docs."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "code-metrics.generated.md"


@dataclass
class LexerState:
    block_depth: int = 0
    raw_hashes: int | None = None


def line_has_code(line: str, state: LexerState) -> bool:
    """Return whether a Rust physical line contains a token outside comments."""
    index = 0
    has_code = state.raw_hashes is not None

    while index < len(line):
        if state.raw_hashes is not None:
            marker = '"' + ('#' * state.raw_hashes)
            end = line.find(marker, index)
            if end < 0:
                return has_code or bool(line[index:].strip())
            has_code = True
            index = end + len(marker)
            state.raw_hashes = None
            continue

        if state.block_depth:
            if line.startswith("/*", index):
                state.block_depth += 1
                index += 2
            elif line.startswith("*/", index):
                state.block_depth -= 1
                index += 2
            else:
                index += 1
            continue

        if line.startswith("//", index):
            break
        if line.startswith("/*", index):
            state.block_depth = 1
            index += 2
            continue
        if line[index].isspace():
            index += 1
            continue

        raw = raw_string_hashes(line, index)
        if raw is not None:
            hashes, content_index = raw
            state.raw_hashes = hashes
            has_code = True
            index = content_index
            continue

        if line[index] == '"':
            has_code = True
            index = skip_quoted_string(line, index + 1)
            continue

        has_code = True
        index += 1

    return has_code


def raw_string_hashes(line: str, index: int) -> tuple[int, int] | None:
    if line[index] != "r":
        return None
    cursor = index + 1
    while cursor < len(line) and line[cursor] == "#":
        cursor += 1
    if cursor >= len(line) or line[cursor] != '"':
        return None
    return cursor - index - 1, cursor + 1


def skip_quoted_string(line: str, index: int) -> int:
    escaped = False
    while index < len(line):
        char = line[index]
        if char == '"' and not escaped:
            return index + 1
        if char == "\\" and not escaped:
            escaped = True
        else:
            escaped = False
        index += 1
    return index


def is_test_file(path: Path) -> bool:
    return "test" in path.stem.lower()


def is_core_file(path: Path) -> bool:
    relative = path.relative_to(ROOT / "kernel" / "src")
    parts = relative.parts
    return not (
        is_test_file(path)
        or (len(parts) > 1 and parts[0:2] == ("task", "drivers"))
        or (parts and parts[0] == "hypervisor")
    )


def count_nloc(paths: list[Path]) -> int:
    total = 0
    for path in paths:
        state = LexerState()
        for line in path.read_text(encoding="utf-8").splitlines():
            total += int(line_has_code(line, state))
    return total


def render() -> str:
    source = ROOT / "kernel" / "src"
    files = sorted(source.rglob("*.rs"))
    production = [path for path in files if not is_test_file(path)]
    core = [path for path in files if is_core_file(path)]
    return f"""# Generated code metrics

<!-- Generated by scripts/generate-code-metrics.py; do not edit by hand. -->

| Metric | Definition | Value |
|---|---|---:|
| Kernel nLOC | Non-blank, non-comment Rust lines under `kernel/src`; excludes files matching `*test*.rs` | **{count_nloc(production):,}** |
| Core kernel nLOC | Kernel nLOC excluding `kernel/src/task/drivers/**` and `kernel/src/hypervisor/**` | **{count_nloc(core):,}** |

The first row is the canonical moving kernel-size metric. The second is the boundary-migration
lens used by Spec 15. Neither number is a substitute for reviewing kernel responsibilities.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"stale generated metrics: run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
