[package]
name = "service-kms"
version = "0.1.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "service-kms"
path = "src/main.rs"
test = false

[dependencies]
api = { path = "../../../libs/api", version = "0.1.0" }
types = { path = "../../../libs/types", version = "0.1.0" }
blake2 = { version = "0.10.6", default-features = false }
constant_time_eq = { version = "0.4.2", default-features = false }

[target.'cfg(target_os = "none")'.dependencies]
ostd = { path = "../../../libs/ostd", version = "0.2.0" }

[build-dependencies]
cell-build = { path = "../../../libs/cell-build", version = "0.2.0" }
